# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll.xci
# IP: The module: 'ocxo_clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ocxo_clk_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'ocxo_clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ocxo_clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll.xci
# IP: The module: 'ocxo_clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ocxo_clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'ocxo_clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/guest/cae/fpga/ntpserver/ip/ocxo_clk_pll/ocxo_clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ocxo_clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
